import dynamical_aspects_statistical_mechanics_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace dynamical_aspects_statistical_mechanics_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end dynamical_aspects_statistical_mechanics_theorem_canonical_lane_mathlib
end HautevilleHouse
